spring.application.name=WarmHelp
spring.config.import=optional:classpath:application-secrets.properties

# Configuracion del puerto de SpringBoot -> por defecto = 8080
#server.port=8080
server.port=${PORT:8080}
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration


# Configuraci?n de Base de Datos
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuraci?n de Hibernate
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Nos permite ver en el terminal la query que se ha ejecutado al consultar una API.
# Esta l?nea solo puede estar en la fase de pruebas
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# OpenAI Config
openai.api.model=gpt-3.5-turbo
server.servlet.context-path=/api

# 1 dia en segundos
jwt.expiration=86400000
jwt.secret=${jwt.secret}

#Config cloudinary for images
cloudinary.url=${CLOUDINARY_URL}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Usado para la parte de email
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}

# *************************************************************************
# Stripe develop
# Descomentar para poder obtener pagos
stripe.api.secret.key=${STRIPE_KEY}
stripe.success.url=http://localhost:4200/success
stripe.cancel.url=http://localhost:4200/cancel