spring.application.name=WarmHelp
spring.config.import=optional:classpath:application-secrets.properties

# Configuracion del puerto de SpringBoot -> por defecto = 8080
#server.port=8080
server.port=${PORT:8080}


# Configuraci?n de Base de Datos
# spring.datasource.url = jdbc:mysql://<IP o localhost>:<Puerto de la BBDD>/{nombre_base_datos}
spring.datasource.url=jdbc:${JDBC_DATABASE_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuraci?n de Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# Nos permite ver en el terminal la query que se ha ejecutado al consultar una API.
# Esta l?nea solo puede estar en la fase de pruebas
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# OpenAI Config
openai.api.model=gpt-3.5-turbo
server.servlet.context-path=/api

# 1 d?a en segundos
jwt.expiration=86400000

# ***********************************************************************
# Usado para la parte de email


spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# *************************************************************************

# *************************************************************************
# Stripe develop
# Descomentar para poder obtener pagos
stripe.api.secret.key=${STRIPE_KEY}
stripe.success.url=http://localhost:4200/success
stripe.cancel.url=http://localhost:4200/cancel