INSERT IGNORE INTO calification (calification_type) VALUES ('EXCELENTE'), ('BUENO'), ('REGULAR'), ('MALO'), ('PESIMO');
INSERT IGNORE INTO currencies (currency_type) VALUES ('USD'), ('EUR'), ('JPY');
INSERT IGNORE INTO incident_states (incident_state) VALUES ('PENDIENTE'), ('EN_PROGRESO'), ('RESUELTA'), ('CERRADA');
INSERT IGNORE INTO incident_types (incident_type) VALUES ('TECNICA'), ('FINANCIERA'), ('OTROS');
INSERT IGNORE INTO report_states (report_state) VALUES ('PENDING'), ('IN_PROGRESS'), ('COMPLETED');
INSERT IGNORE INTO report_types (report_type) VALUES ('BULLYING_OR_HARASSMENT'), ('SUICIDE_SELF_INJURY_OR_EATING_DISORDERS'), ('VIOLENCE'), ('ILLEGAL_SALES'), ('NUDITY_OR_SEXUAL_ACTIVITY'), ('SCAMS_FRAUD_OR_SPAM'), ('FALSE_INFORMATION');
INSERT IGNORE INTO role (role_type) VALUES ('CLIENT'), ('ADMIN'), ('PROFESSIONAL');
